export const portfolios = [
    {
        id: 1,
        category: 'Typescript',
        image: './assets/googl.png',
        github: 'https://github.com/supriya224/googleSearchEngine-clone',
        linkedin: 'https://main--thunderous-florentine-bb3b72.netlify.app/',
        title: 'Google clone',
        text: 'Nextjs,Typescript,React, TailwindCss',
    },
    {
        id: 2,
        category: 'Reactjs',
        image: './assets/code.png',
        github: 'https://github.com/supriya224/codepen-clone',
        linkedin: 'https://supriya224.github.io/codepen-clone/',
        title: 'Codepen clone',
        text: 'React,React-codemirror2',
    },
    {
        id: 3,
        category: 'Typescript',
        image: './assets/music.png',
        github: 'https://github.com/supriya224/Music-App',
        linkedin:
            'https://supriya224.github.io/Music-App/',
        title: 'My own Music playlist-web-app',
        text: `ReactJs, Typescript, IndexDB, TailwindCss`,
    },
    {
        id: 4,
        category: 'Reactjs',
        image: './assets/note.png',
        github: 'https://github.com/supriya224/notes-web-app',
        linkedin: 'https://supriya224.github.io/notes-web-app/',
        title: 'React Notes-Web-App',
        text: 'ReactJs, ReactHooks, TailwindCss',
    },

    {
        id: 13,
        category: 'Typescript',
        image: './assets/admin.png',
        github: ' https://github.com/supriya224/Admin-Dashboard-typescript',
        linkedin:
            'https://elegant-stroopwafel-e2b1f6.netlify.app/',
        title: 'TailAdmin-clone-app',
        text: `vite+ReactJs, Typescript,TailwindCss ReactHooks,React-router-dom,react-apexcharts,flatpickr,apexcharts`,
    },
    {
        id: 5,
        category: 'Javascript',
        image: './assets/dic.png',
        github: 'https://github.com/supriya224/dictinoryApp',
        linkedin: 'https://supriya224.github.io/dictinoryApp/',
        title: 'Dictionary-Web-App',
        text: 'HTML, Css, Javascript, Dictionary-api',
    },
    {
        id: 10,
        category: 'Reactjs',
        image: './assets/nike.png',
        github: 'https://github.com/supriya224/Nike-Store',
        linkedin: 'https://unique-torrone-70b350.netlify.app/',
        title: 'Nike-store',
        text: 'Vite+ReactJs, Redux,ReactHooks,lodash,Splider, TailwindCss,',
    },
    {
        id: 9,
        category: 'Javascript',
        image: './assets/quote.png',
        github: ' https://github.com/supriya224/quotoGenerator',
        linkedin: 'https://courageous-hummingbird-dae033.netlify.app/',
        title: 'Quote Generator Web-App',
        text: 'HTML, Css, Javascript, Quote-api',
    },

    {
        id: 6,
        category: 'Javascript',
        image: './assets/game.png',
        github: 'https://github.com/supriya224/2048Game',
        linkedin: 'https://supriya224.github.io/2048Game/',
        title: '2028 Game',
        text: 'HTML, Css, Javascript',
    },

    {
        id: 11,
        category: 'Reactjs',
        image: './assets/ecom.png',
        github: 'https://github.com/supriya224/E-Commerece-web-app',
        linkedin: 'https://supriya224.github.io/E-Commerece-web-app/',
        title: 'E-Commerece',
        text: 'ReactJs, ReactHooks, TailwindCss',
    },
    {
        id: 7,
        category: 'Javascript',
        image: './assets/joke.png',
        github: 'https://github.com/supriya224/jokeGenerator',
        linkedin: 'https://supriya224.github.io/jokeGenerator/',
        title: 'joke-web-App',
        text: 'HTML, Css, Javascript, joke-api',
    },
    {
        id: 8,
        category: 'Javascript',
        image: './assets/product.png',
        github: 'https://github.com/supriya224/product-filter',
        linkedin: 'https://brilliant-fairy-6d3109.netlify.app/',
        title: 'ECommerec product-filter',
        text: 'HTML, Css ,Javascript',
    },
    {
        id: 12,
        category: 'Reactjs',
        image: './assets/zomato.png',
        github: 'https://github.com/supriya224/zomato-clone-app',
        linkedin:
            '//astounding-alfajores-34473b.netlify.app/',
        title: 'Zomato-Clone',
        text: `ReactJs, ReactHooks,React-Router,Css`,
    },


]
